import { useMutation, useQuery } from "@tanstack/react-query";
import { createSecurityExportTask, downloadSecurityExportTask, getAdminMetrics, getAdminReviewRiskSummary, getPaymentReplaySummary } from "@suno/shared";
import { apiOptions, sessionApiOptions } from "../lib/auth";
import { useState } from "react";

const COUNT_TONES = ["tone-lime", "tone-amber", "tone-rose", "tone-blue"];

export function AdminDashboardPage() {
  const metricsQuery = useQuery({ queryKey: ["admin-metrics"], queryFn: () => getAdminMetrics(sessionApiOptions()) });
  const replayQuery = useQuery({ queryKey: ["payment-replay-summary"], queryFn: () => getPaymentReplaySummary(sessionApiOptions()) });
  const riskQuery = useQuery({ queryKey: ["review-risk-summary"], queryFn: () => getAdminReviewRiskSummary(sessionApiOptions()) });
  const [exportStatus, setExportStatus] = useState("");
  const [exportTask, setExportTask] = useState<Record<string, unknown> | null>(null);
  const exportMutation = useMutation({ mutationFn: () => createSecurityExportTask({ type: "summary", format: "csv", lookbackMinutes: 60, topN: 10, idempotencyKey: `suno-export-${Date.now()}` }, sessionApiOptions()), onSuccess: (result) => { setExportTask(result); setExportStatus(`${String(result.status ?? "已创建")} · ${String(result.fileName ?? result.taskId ?? "任务已提交")}`); }, onError: () => setExportStatus("导出任务创建失败，请稍后重试。") });
  const downloadMutation = useMutation({ mutationFn: () => downloadSecurityExportTask(String(exportTask?.taskId ?? ""), sessionApiOptions()), onSuccess: (content) => { const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = String(exportTask?.fileName ?? "security-events-summary.csv"); anchor.click(); URL.revokeObjectURL(url); setExportStatus(`${String(exportTask?.fileName ?? "导出文件")} · 已下载`); } });
  const exportTaskId = String(exportTask?.taskId ?? "");
  const metrics = metricsQuery.data;
  const countEntries = Object.entries(metrics?.counts ?? {});
  const loading = metricsQuery.isLoading || replayQuery.isLoading || riskQuery.isLoading;
  return <div className="admin-page"><div className="admin-topbar"><div><p className="eyebrow">Suno operations</p><h1>今天，系统流转得很好。</h1></div><span className="admin-live"><i /> {apiOptions.demo ? "Demo data live" : "Live data"}</span></div>{metricsQuery.isError || replayQuery.isError || riskQuery.isError ? <div className="empty-state"><p>运营指标暂时无法加载，请检查权限或网络后重试。</p><button className="button button-dark" onClick={() => { void metricsQuery.refetch(); void replayQuery.refetch(); void riskQuery.refetch(); }}>重新加载 ↗</button></div> : <div className="metric-grid"><Metric label="安全事件（24h）" value={loading ? "—" : metrics?.totalEvents ?? 0} suffix="件" tone="lime" /><Metric label="重放队列待处理" value={loading ? "—" : replayQuery.data?.pending ?? 0} suffix="单" tone="amber" /><Metric label="重放死信" value={loading ? "—" : replayQuery.data?.dead ?? 0} suffix="单" tone="rose" /><Metric label="评论待处理报告" value={loading ? "—" : riskQuery.data?.pendingReportCount ?? 0} suffix="条" tone="blue" /></div>}<div className="admin-columns"><section className="admin-panel"><div className="panel-heading"><h2>安全事件分布（24h）</h2><div className="panel-actions"><button className="text-button" onClick={() => exportMutation.mutate()} disabled={exportMutation.isPending}>{exportMutation.isPending ? "正在生成…" : "生成导出任务 ↗"}</button>{exportTaskId && <button className="text-button" onClick={() => downloadMutation.mutate()} disabled={downloadMutation.isPending}>{downloadMutation.isPending ? "正在下载…" : "下载导出文件 ↘"}</button>}</div></div>{exportStatus && <p className="export-status">{exportStatus}</p>}{downloadMutation.isError && <p className="error-message admin-error">导出文件下载失败，请稍后重试。</p>}{metrics?.recommendation && <p className="panel-note">{metrics.recommendation}</p>}<div className="activity-list">{countEntries.map(([action, count], index) => <div className="activity-row" key={action}><i className={COUNT_TONES[index % COUNT_TONES.length]} /><span>{action}</span><strong>{count}</strong><small>次</small></div>)}{!loading && countEntries.length === 0 && <p className="muted">当前窗口暂无安全事件。</p>}</div></section><section className="admin-panel dark-panel"><p className="eyebrow">循环看板</p>{apiOptions.demo ? <><h2>本周每一件被重新选择的物品，都少了一点浪费。</h2><div className="admin-chart"><span style={{ height: "34%" }} /><span style={{ height: "58%" }} /><span style={{ height: "46%" }} /><span style={{ height: "72%" }} /><span style={{ height: "64%" }} /><span style={{ height: "91%" }} /><span style={{ height: "78%" }} /></div><div className="chart-labels"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span></div></> : <><h2>流转趋势</h2><p className="muted">图表数据需接入后端统计接口后展示，当前不渲染演示数据。</p></>}</section></div></div>;
}

function Metric({ label, value, suffix, tone }: { label: string; value: number | string; suffix: string; tone: string }) {
  return <div className={`metric-card metric-${tone}`}><span>{label}</span><strong>{value}<small>{suffix}</small></strong><p>实时同步后端</p></div>;
}
